mutation PasswordReset(
  $token: String!,
  $password: String!
  $password_confirmation: String!
) {
  password_reset(input: {
    token: $token,
    password: $password,
    password_confirmation: $password_confirmation
  }) {
    token {
      api_token,
      expires_in
    },
    user {
      first_name,
      last_name,
      email,
      username,
      email_verified
    }
  }
}