mutation UpdatePassword(
  $old_password: String!
  $new_password: String!
  $new_password_confirmation: String!
) {
  update_password(input: {
    old_password: $old_password,
    new_password: $new_password,
    new_password_confirmation: $new_password_confirmation
  })
}