mutation Verify(
  $token: String!
) {
  verify(token: $token) {
    token {
      api_token,
      expires_in
    },
    user {
      first_name,
      last_name,
      email,
      username,
      email_verified
    }
  }
}